/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DualIndexRouteImport } from './routes/dual/index'
import { Route as GauntletIndexRouteImport } from './routes/gauntlet/index'
import { Route as SampleIndexRouteImport } from './routes/sample/index'
import { Route as SccIndexRouteImport } from './routes/scc/index'
import { Route as StreakIndexRouteImport } from './routes/streak/index'
import { Route as TimedIndexRouteImport } from './routes/timed/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DualIndexRoute = DualIndexRouteImport.update({
  id: '/dual/',
  path: '/dual/',
  getParentRoute: () => rootRouteImport,
} as any)
const GauntletIndexRoute = GauntletIndexRouteImport.update({
  id: '/gauntlet/',
  path: '/gauntlet/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleIndexRoute = SampleIndexRouteImport.update({
  id: '/sample/',
  path: '/sample/',
  getParentRoute: () => rootRouteImport,
} as any)
const SccIndexRoute = SccIndexRouteImport.update({
  id: '/scc/',
  path: '/scc/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakIndexRoute = StreakIndexRouteImport.update({
  id: '/streak/',
  path: '/streak/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimedIndexRoute = TimedIndexRouteImport.update({
  id: '/timed/',
  path: '/timed/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dual/': typeof DualIndexRoute
  '/gauntlet/': typeof GauntletIndexRoute
  '/sample/': typeof SampleIndexRoute
  '/scc/': typeof SccIndexRoute
  '/streak/': typeof StreakIndexRoute
  '/timed/': typeof TimedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dual': typeof DualIndexRoute
  '/gauntlet': typeof GauntletIndexRoute
  '/sample': typeof SampleIndexRoute
  '/scc': typeof SccIndexRoute
  '/streak': typeof StreakIndexRoute
  '/timed': typeof TimedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dual/': typeof DualIndexRoute
  '/gauntlet/': typeof GauntletIndexRoute
  '/sample/': typeof SampleIndexRoute
  '/scc/': typeof SccIndexRoute
  '/streak/': typeof StreakIndexRoute
  '/timed/': typeof TimedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dual/'
    | '/gauntlet/'
    | '/sample/'
    | '/scc/'
    | '/streak/'
    | '/timed/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dual' | '/gauntlet' | '/sample' | '/scc' | '/streak' | '/timed'
  id:
    | '__root__'
    | '/'
    | '/dual/'
    | '/gauntlet/'
    | '/sample/'
    | '/scc/'
    | '/streak/'
    | '/timed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DualIndexRoute: typeof DualIndexRoute
  GauntletIndexRoute: typeof GauntletIndexRoute
  SampleIndexRoute: typeof SampleIndexRoute
  SccIndexRoute: typeof SccIndexRoute
  StreakIndexRoute: typeof StreakIndexRoute
  TimedIndexRoute: typeof TimedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual/': {
      id: '/dual/'
      path: '/dual'
      fullPath: '/dual/'
      preLoaderRoute: typeof DualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauntlet/': {
      id: '/gauntlet/'
      path: '/gauntlet'
      fullPath: '/gauntlet/'
      preLoaderRoute: typeof GauntletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/': {
      id: '/sample/'
      path: '/sample'
      fullPath: '/sample/'
      preLoaderRoute: typeof SampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scc/': {
      id: '/scc/'
      path: '/scc'
      fullPath: '/scc/'
      preLoaderRoute: typeof SccIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak/': {
      id: '/streak/'
      path: '/streak'
      fullPath: '/streak/'
      preLoaderRoute: typeof StreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timed/': {
      id: '/timed/'
      path: '/timed'
      fullPath: '/timed/'
      preLoaderRoute: typeof TimedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DualIndexRoute: DualIndexRoute,
  GauntletIndexRoute: GauntletIndexRoute,
  SampleIndexRoute: SampleIndexRoute,
  SccIndexRoute: SccIndexRoute,
  StreakIndexRoute: StreakIndexRoute,
  TimedIndexRoute: TimedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
