/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GauntletIndexRouteImport } from './routes/gauntlet/index'
import { Route as StreakIndexRouteImport } from './routes/streak/index'
import { Route as TimedIndexRouteImport } from './routes/timed/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GauntletIndexRoute = GauntletIndexRouteImport.update({
  id: '/gauntlet/',
  path: '/gauntlet/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakIndexRoute = StreakIndexRouteImport.update({
  id: '/streak/',
  path: '/streak/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimedIndexRoute = TimedIndexRouteImport.update({
  id: '/timed/',
  path: '/timed/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gauntlet/': typeof GauntletIndexRoute
  '/streak/': typeof StreakIndexRoute
  '/timed/': typeof TimedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gauntlet': typeof GauntletIndexRoute
  '/streak': typeof StreakIndexRoute
  '/timed': typeof TimedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gauntlet/': typeof GauntletIndexRoute
  '/streak/': typeof StreakIndexRoute
  '/timed/': typeof TimedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gauntlet/' | '/streak/' | '/timed/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gauntlet' | '/streak' | '/timed'
  id: '__root__' | '/' | '/gauntlet/' | '/streak/' | '/timed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GauntletIndexRoute: typeof GauntletIndexRoute
  StreakIndexRoute: typeof StreakIndexRoute
  TimedIndexRoute: typeof TimedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauntlet/': {
      id: '/gauntlet/'
      path: '/gauntlet'
      fullPath: '/gauntlet/'
      preLoaderRoute: typeof GauntletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak/': {
      id: '/streak/'
      path: '/streak'
      fullPath: '/streak/'
      preLoaderRoute: typeof StreakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timed/': {
      id: '/timed/'
      path: '/timed'
      fullPath: '/timed/'
      preLoaderRoute: typeof TimedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GauntletIndexRoute: GauntletIndexRoute,
  StreakIndexRoute: StreakIndexRoute,
  TimedIndexRoute: TimedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
